### ISSUE TITLE
PyTorch version is too old on macOS (0.4.1 instead of 1.9.0)

### ISSUE THREAD

**Issue by fepegar** [pmeier/light-the-torch#34]
Hello again!

I'm having some issues, this time on macOS.

```shell
$ pip install torch                                
Collecting torch
  Using cached torch-1.9.0-cp36-none-macosx_10_9_x86_64.whl (127.9 MB)
```

```shell
$ ltt install torch                                                                                      
Collecting torch==0.4.1
  Using cached https://download.pytorch.org/whl/torch-0.4.1-cp36-cp36m-macosx_10_7_x86_64.whl (11.5 MB)
```

**Comment by fepegar** [comment]
(let me know if you need any more info, or there's anything you'd like me to try)

**Comment by pmeier** [comment]
That is unfortunate. I already found the offender, but I'm not sure what a good way forward from here would be:

 From `1.0.0` the macOS wheels are tagged with `+cpu`. Before they are not tagged with any local specifier which means they can run on any computation backend. The order of precedence of the backends is CPU < CUDA < Any. Since #33 established that we prefer a more fitting backend before the version, `(Any, 0.4.1) > (CPU, 1.9.0)`. 

A fix could be to manually patch macOS versions that predate `1.0.0` to add the `+cpu` specifier. Let me look into that if it is possible.
