### ISSUE TITLE
ltt install torchvision installs a very old version of torchvision

### ISSUE THREAD

**Issue by fepegar** [pmeier/light-the-torch#36]
Hi @pmeier, it's me again. I was just trying to use `ltt` to install PyTorch and TorchVision on my Linux laptop. My command is `ltt install torchvision`. It installs `https://download.pytorch.org/whl/cu101/torch-1.8.1%2Bcu101-cp38-cp38-linux_x86_64.whl`, as expected for my drivers, but only `https://download.pytorch.org/whl/torchvision-0.2.0-py2.py3-none-any.whl`. I was expecting `torchvision==0.9.0`. I see on the [PyTorch website](https://pytorch.org/get-started/previous-versions/) that PyTorch 1.8.1 is not listed. Could that be related? Anyway, I thought you should know.

**Comment by pmeier** [comment]
Hey @fepegar. This comes down to the same as #34: `(Any, 0.2.0) > (CUDA 10.1, 0.9.0).` I need to think about a better way to order the priority. If you have some thoughts, happy to hear them.

**Comment by pmeier** [comment]
I think in the current state (and likely in the future), we can safely replace the `AnyBackend` with a `CPUBackend`. This should work, because the `AnyBacked` is usually only for old releases that did not yet include compiled code. This will only become a problem if package later on removes compiled code and becomes pure Python again. I conjecture this will not happen, since the PyTorch folk values BC quite high.
