### ISSUE TITLE
Support newer versions of `pip`

### ISSUE THREAD

**Issue by jamesobutler** [pmeier/light-the-torch#40]
As of https://github.com/pmeier/light-the-torch/commit/24cd4744fac964923b0ad98a906cc67b725ab338, the latest versions of `pip` are not supported. The latest version supported is v20.2.4 which was released October 16th, 2020. That was about 1.25 years ago. This is starting to become an unreasonable pinning of `pip` as there are many improvements that cannot be used and `pip` has to be downgraded specifically to install `light-the-torch`.

https://github.com/pmeier/light-the-torch/blob/dfbd56ebbc57b91dfcba2e23121a6a75705643d8/setup.cfg#L32-L33

@pmeier I haven't been able to find in the repo yet the reason behind this pinning of the version. 

`pip` release notes are available to review at https://pip.pypa.io/en/stable/news/.

**Comment by pmeier** [comment]
> I haven't been able to find in the repo yet the reason behind this pinning of the version.

The pinning is not unreasonable since we depend on `pip` internals and newer versions actually break `light-the-torch`. But you are right in the sense that this means `light-the-torch` is also outdated. I'll see if I can find some time over the weekend to port to a newer version.

**Comment by pmeier** [comment]
`pip==22.0` was just released and I started porting towards supporting it. I think I'm mostly done, but now we have another problem: pytorch/pytorch#72045. As long as this isn't fixed, `light-the-torch` won't work, because it basically automates these custom commands. Given that this will affect a lot of users, I'm guessing this will be fixed quick. I'll get back to you afterwards.

**Comment by jamesobutler** [comment]
That makes sense! `pip` 22.x versions matching with the year 2022, should give a good amount of support for the rest of the year.

**Comment by pmeier** [comment]
It seems they are taking quite a while to resolve this. I'll make an update to `pip==21.3.*`. That should be also sufficient for your use case, given that it was the latest version when you opened the issue, right?

**Comment by jamesobutler** [comment]
As far as I know PyTorch is working appropriately with latest `pip` now, it is just specifically `pip==22.0.0` that didn't work.

**Comment by pmeier** [comment]
True, I can simply exclude the breaking versions. Still, some of my down-stream projects are stuck in Python 3.6 until PyTorch finally drops support for it. I think I'll still do `21.3.*` first and upgrade again if I can depend on Python 3.7.

**Comment by jamesobutler** [comment]
As a heads up the latest tag of PyTorch, 1.11.0-rc2, requires Python 3.7+ (https://github.com/pytorch/pytorch/blob/v1.11.0-rc2/setup.py#L209). Based on the current release candidate number and based on the past current cadence of 4 months between new minor version releases, that means PyTorch is likely to cut a stable release of 1.11.0 soon.

**Comment by pmeier** [comment]
Yeah, release is planned for late February / early March.

**Comment by jamesobutler** [comment]
Feel free to update this repo for 21.3.* support now and then again for 22.x.x (minus 22.0.0/22.0.1) in a few weeks when the new PyTorch is released. That's good with me 👍🏻

**Comment by pmeier** [comment]
I'm sorry that this is taking so long. I'm having troubles with the new dependency resolver and PyTorch and I'm not yet sure which side is to blame. Are you aware of any known issues?

**Comment by pmeier** [comment]
Just to report some progress: since the dependency resolver can only access a packages meta data such as dependency after it is already downloaded, the current way of using the default resolution, extracting the PyTorch dists and terminate at this point will no longer work. Thus, I need to patch the actual resolving by manually inserting this meta data in the right place. 

This is a lot harder than I thought this upgrade will be. I definitely needs to happen going forward, but I need to figure out a good way to do that. In particular, this means that `ltt extract` and `ltt find` will go away, since I'm not going to manually patch / maintain the whole dependency tree. Would that be an issue for your use case or are you only interested in `ltt install` anyway?

**Comment by jamesobutler** [comment]
Yes `ltt install` is my only use case so if the other options go away that is fine with me.

**Comment by jamesobutler** [comment]
PyTorch 1.11.0 is out now which requires Python 3.7+

https://github.com/pytorch/pytorch/tree/v1.11.0

**Comment by pmeier** [comment]
I'm aware. Sorry this is taking so long :disappointed: I have a prototype locally and my goal for this weekend is to at least cut a pre-release.

The real blocker is that I have no idea how to test the new behavior. Since the resolving actually downloads stuff, but I need to test resolved result, I somehow need to mock the download. And this is messy.

**Comment by pmeier** [comment]
Development is happening on the [`rewrite` branch](https://github.com/pmeier/light-the-torch/tree/rewrite).

**Comment by pmeier** [comment]
I just pushed a pre-release. You can install it with `pip install --pre light-the-torch`. Let me know if it works for you. I'll keep working on adding a proper test suite for it.

**Comment by jamesobutler** [comment]
@pmeier Great work on your recent improvements and automation for this repo! Do you have an idea when you might create a stable release? I see you're up to `v0.4.0rc7` and I'm sure others would like to use `pip install light-the-torch` using newer versions of pip without having to specify `--pre` to get a release candidate.

**Comment by pmeier** [comment]
Done :tada: `pip install light-the-torch` will now give you `0.4.0`.
